#!/usr/bin/env python3
"""generate the overlay keychar maps from the stock TitanKey.kcm.

the titan's printed alt layer covers 16 of the 32 ascii symbols; this adds the other 16
on a modifier layer, plus vi arrows and escape. it is pure data — the input system reads
it, so there is no process, no accessibility hook and nothing that can eat a keypress.

three layouts ship in one apk so a parse failure in one cannot take the others down, and
so the modifier can be changed without a rebuild:
  titan_dual      symbols on BOTH ctrl+letter and fn+letter. the key next to shift emits
                  KEYCODE_CTRL_LEFT (113) — measured, not assumed. Fn is set to "Sym key" in
                  the oem shortcut-key settings so it emits KEYCODE_SYM (63), a modifier no
                  app or terminal claims; ctrl is the fast one-finger chord everywhere else,
                  and termux owns ctrl, so fn is the route that works inside a shell.
  titan_sym       fn only, for when a stray ctrl chord causes trouble

an overlay replaces a key wholesale, so every touched key is restated in full.
PROBE adds an unmistakable no-modifier change so "is the overlay applied at all" can be
told apart from "is this modifier tracked". set it False once the mechanism is proven.
"""
import re
from pathlib import Path

HERE = Path(__file__).parent
SRC = HERE / "TitanKey.orig.kcm"
RAW = HERE / "res/raw"

PROBE = False  # alt+K probe: proved the overlay applies (aug 7 2026); off for daily use

# the 16 ascii symbols the titan's printed alt layer leaves out
SYMBOLS = {
    "W": "~", "E": "=", "T": "{", "Y": "}", "I": "|", "O": "\\", "P": ";",
    "S": "$", "D": "%", "F": "^", "G": "`", "X": "&", "C": "[", "V": "]",
    "B": "<", "N": ">",
}

# keys that emit a real keycode instead of a character. `replace` swaps the keycode
# at the input reader, so these reach the system the same way a hardware key would.
NAV = {"H": "DPAD_LEFT", "J": "DPAD_DOWN", "K": "DPAD_UP", "L": "DPAD_RIGHT",
       "Q": "ESCAPE", "A": "TAB",
       "M": "HOME", "R": "APP_SWITCH", "U": "NOTIFICATION", "Z": "SLEEP"}

HEADER = """# titan-layout — {desc}
# generated by gen.py from /system/usr/keychars/TitanKey.kcm; do not hand-edit.

type OVERLAY
"""


def literal(ch):
    return "'%s'" % ch.replace("\\", "\\\\").replace("'", "\\'")


def emit(name, desc, modifiers, nav=False):
    src = SRC.read_text()
    out = [HEADER.format(desc=desc)]
    for key, body in re.findall(r"key ([A-Z]+) \{(.*?)\n\}", src, re.S):
        value = None
        if key in SYMBOLS:
            value = literal(SYMBOLS[key])
        elif nav and key in NAV:
            value = "replace " + NAV[key]

        if key == "SPACE":
            # the stock map parks the oem symbol-picker char on alt+space
            body = body.replace("'\\uef01'", "' '")
        elif PROBE and key == "K":
            body = body.replace("'\"'", "'\\u00a2'")
        elif value is None:
            continue

        if value is not None:
            # the stock map already declares shift+alt as none — drop that row rather than
            # appending, or the combination is defined twice and the whole file fails to parse
            if any(m.startswith("shift+alt") for m in modifiers):
                body = re.sub(r"\n *shift\+alt.*", "", body)
            body = body.rstrip("\n")
            for m in modifiers:
                body += "\n    %-36s%s" % (m + ":", value)
        out.append("key %s {%s\n}\n" % (key, body))
    (RAW / name).write_text("\n".join(out))
    print("%-22s %2d keys" % (name, len(out) - 1))


emit("titan_dual.kcm", "symbols, arrows and escape on ctrl and on fn(sym)",
     ["ctrl", "sym"], nav=True)
emit("titan_sym.kcm", "symbols, arrows and escape on fn(sym) only",
     ["sym"], nav=True)
